# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Eduardo Gonçalves Costa
author-title: Full Stack Developer
gravatar: 3b2729268c78151e55c08f54d1151e94
email: eduardogc@outlook.com
twitter: geceduardo2
github: eduardogc
facebook: geceduardo
linkedin: geceduardo/br
bio: "Brazilian JavaScript developer.
      I graduated in Computer Science at Federal University of Uberlândia.
      I like to work mainly with JavaScript frameworks or just pure JavaScript, but I also work with many languages, frameworks and technologies."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 4
  - name: CSS 3
    level: 4
  - name: JavaScript
    level: 4
  - name: jQuery
    level: 4
  - name: Angular
    level: 4
  - name: Vue.js
    level: 1
  - name: Bootstrap
    level: 4
  - name: Materialize CSS
    level: 3
  - name: LESS
    level: 3
  - name: SASS
    level: 3
  - name: Stylus
    level: 3
  - name: Gulp
    level: 3
  - name: Grunt
    level: 4
  - name: Bower
    level: 3
  - name: React
    level: 1
  - name: Redux
    level: 1
  - name: Webpack
    level: 1

back-end:
  - name: Java
    level: 3
  - name: Node.js
    level: 2

mobile:
  - name: Android
    level: 3
  - name: iOS
    level: 1

db:
  - name: MySQL
    level: 3
  - name: PostgreSQL
    level: 3
  - name: MongoDB
    level: 2
  - name: SQL Server
    level: 3
  - name: Oracle
    level: 3
  - name: Firebase
    level: 3
  - name: SqLite
    level: 3

devops:
  - name: Docker
    level: 1
  - name: Kubernetes
    level: 1
  - name: Jenkins
    level: 1
  - name: Git
    level: 5
  - name: Continuous Integration
    level: 1
  - name: Continuous Delivery
    level: 1

methodologies:
  - name: Agile Methodologies
    level: 5
  - name: Scrum
    level: 5
  - name: RUP
    level: 4

others:
  - name: Web Services
    level: 4
  - name: REST
    level: 4
  - name: JEE, JSF, JPA, EJB, CDI
    level: 3
  - name: Ruby on Rails
    level: 3
  - name: MEAN Stack
    level: 2
  - name: VRaptor
    level: 2
  - name: Play Framework
    level: 2

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap]
